### PR TITLE
Model Service completed

### PR DESCRIPTION
**Pull request by RodinHaker**
Created a REST API to query the model.
It also creates a docker image which you can pull from Packages.

### CODE REVIEW

**Comment by tpenning** [comment]
You're missing the Windows/Intel tensorflow building package `tensorflow-intel = {version = "^2.16.1", markers = "sys_platform == 'win32'"}` in the pyproject.toml file, currently it won't work on Windows

**Comment by tpenning** [comment]
Heartbeat is misspelled in `HearbeatResult` and `get_hearbeat`

**Comment by RodinHaker** [comment]
All mentioned issues are resolved. I have also remove GPU compatibility as the image was over 20GB, which is way too big. Now the latest image has the tag 'latest' as well

**Comment by ahasami** [comment]
> All mentioned issues are resolved. I have also remove GPU compatibility as the image was over 20GB, which is way too big. Now the latest image has the tag 'latest' as well

I think the readme still needs to be updated? as it only mentions GPU now

**Comment by RodinHaker** [comment]
> > All mentioned issues are resolved. I have also remove GPU compatibility as the image was over 20GB, which is way too big. Now the latest image has the tag 'latest' as well
> 
> I think the readme still needs to be updated? as it only mentions GPU now

Should all be gone now

**Comment by tpenning** [comment]
In the readme there is this line `Then go to http://localhost:8000/docs.`
This needs to be updated to use port 8080 which the Github Package registry will use

**Review by tpenning — APPROVED** [review]
The code looks good and the readme is clear. Following it I was able to run the application using both the GitHub image and locally running it. Then I was able to authorize and make requests to both /heartbeat and /predict which both worked as they should, this can be merged

**Pull request merged**
